name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service bf1b60c9-0ef6-4a08-bb90-aacfca29e417 --environment b9cc9ddb-5dc1-497d-b480-d20d8d181149 --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
